name: GraalVM build
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Print env
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn --version
      - name: Maven package basic
        run: mvn -Pall clean package
      - name: Create native need config files
        run: |
          cp restore.yml ./target
          cd target
          java -agentlib:native-image-agent=config-output-dir=../src/main/resources/META-INF/native-image -jar Restore-all.jar
      - name: Maven package native
        run: |
          mvn -Pnative package
          cd target
          ls
      - name: Prepare Release File (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cp target/Restore ./
      - name: Prepare Release File (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          copy target/Restore.exe ./
          copy target/Restore-all.jar ./
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Restore*