name: GraalVM build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Print env
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn --version
      - name: Maven package basic
        run: mvn -Pall clean package
      - name: Create native need config files
        run: |
          cp restore.yml ./target
          cd target
          ll
          pwd
          java -agentlib:native-image-agent=config-output-dir=../src/main/resources/META-INF/native-image -jar Restore-all.jar
      - name: Maven package native
        run: mvn -Pnative clean package